#!/bin/bash

# This script generates a Swift file with the API key from Config.xcconfig
# It should be run as a build phase script in Xcode

# Get the script directory
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_DIR="$( cd "$SCRIPT_DIR/.." && pwd )"

# Path to Config.xcconfig
CONFIG_FILE="$PROJECT_DIR/MarketMood/Config.xcconfig"

# Output Swift file
OUTPUT_FILE="$PROJECT_DIR/MarketMood/APIKey.swift"

# Read API_KEY from Config.xcconfig
if [ -f "$CONFIG_FILE" ]; then
    # Extract API_KEY value (handles both API_KEY = value and API_KEY=value formats)
    API_KEY=$(grep "^API_KEY" "$CONFIG_FILE" | sed 's/^API_KEY[[:space:]]*=[[:space:]]*//' | tr -d '\n\r')
    
    if [ -z "$API_KEY" ]; then
        echo "error: API_KEY not found in Config.xcconfig"
        exit 1
    fi
    
    # Generate Swift file
    cat > "$OUTPUT_FILE" <<EOF
//
//  APIKey.swift
//  MarketMood
//
//  This file is auto-generated by the build script.
//  Do not edit manually.
//

import Foundation

enum APIKey {
    static let value: String = "$API_KEY"
}
EOF
    
    echo "Generated APIKey.swift with API key from Config.xcconfig"
else
    echo "error: Config.xcconfig not found at $CONFIG_FILE"
    exit 1
fi

